name: PlayerLocator
main: com.vokal.locator.PlayerLocator
version: 1.0
description: Lalalaa

commands:
  locations:
    description: Administrate locations
    usage: /<command> [server|port] value
  fart:
    description: Makes you fart
    usage: /<command>
  gob:
    description: Runs the Gob program
    usage: /<command>
